# 20.04 is a LTS (long-term support) version

FROM ubuntu:20.04

LABEL maintainer="Julian Zhou [jqzhou@email.wustl.edu]" \
      description="Minimal ubuntu"

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
    sudo \
    wget \
    tree \
    less
