# 20.04 is a LTS (long-term support) version

FROM ubuntu:20.04

LABEL maintainer="Julian Zhou [jqzhou@wustl.edu]" \
      description="Cell Ranger v8.0.1 for LSF"

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
    sudo \
    wget

# WORKDIR sets the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD
# instructions that follow it

WORKDIR /usr/src/

ARG CR_NAME="cellranger-8.0.1"

ARG CR_LINK="https://cf.10xgenomics.com/releases/cell-exp/cellranger-8.0.1.tar.gz?Expires=1724491298&Key-Pair-Id=APKAI7S6A5RYOXBWRPDA&Signature=jSrXr3BHFiLwOtphdQpfVRSuk6sf2UwVOZN0TSnpt4QnANNaGoU3uNMTA~nPuftUfmZuaq1jWwI2QbnKhqBULluDN-K4iQVdx1KZuZALsZ~TJj9Flf-J8LkEf3q1VRNZNzRISUyNu0iuMob--7hHxKg8I2lBxP5VJm7QpQu-7UpaTS~LvaLsNB--p775JiS9X3a6whUxlugx~h7k2GBYDvzz5GelAOB-FMwuRhJ-FYWXTcfhRUNupESxuTtnbzRRkTOizZmejmE8p-OqnOgPTgLFv6zOxZ5NUaF8EscUyJJy5bH-NSbcNWEr5T-6yUQKIoBLyNoxrE2YP1LhmkFLsA__"

RUN wget --no-check-certificate -O "${CR_NAME}.tar.gz" "${CR_LINK}" && \
	tar -zxvf "${CR_NAME}.tar.gz" && \
	rm "${CR_NAME}.tar.gz"

# LSF system needs this
ENTRYPOINT ["/bin/sh"]

ENV PATH="/usr/src/${CR_NAME}:${PATH}"

# BM: 
# Based on your compute solution, you might need to set compute environment 
# variable to FALSE during scripting. This will allow the container to execute 
# the ENV command and add cellranger to PATH.
